create table if not exists image_info (
     height integer,
     image_format smallint check (image_format between 0 and 1),
     image_type smallint check (image_type between 0 and 0),
     width integer,
     created_at timestamp(6) with time zone,
     file_size bigint,
     id bigint generated by default as identity,
     member_id uuid,
     primary key (id)
);

create table if not exists image_file_access_point (
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    image_id bigint,
    upload_key uuid,
    primary key (id)
);

alter table if exists image_file_access_point
   add constraint image_file_access_point_image_id_fk
   foreign key (image_id)
   references image_info;

