@startuml

'actor User

class Attachment {
    - id: UUID
    - type: AttachmentType
    - resourceId: UUID
}

class NotificationCreateRequest{
    - content: String
    - type: NotificationType
    - files: List<UUID>
}
'    - attachments: List<AttachmentVo>
'}

' /api/v1/notification-group/{group-id}/notifications/{notification-id}/attachments
' put

' /api/v1/files/group-shared/{file-id}
' response
' { fileId: uuid, format: pdf,  size: 123124, url: "실제 접근 경로" }




@enduml