apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: default
  labels:
    app: kafka
spec:
  serviceName: kafka-svc
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
        - name: init-set-broker-id
          image: busybox
          command:
            - sh
            - -c
            - >
              ordinal=$(hostname | awk -F'-' '{print $NF}');
              echo "KAFKA_BROKER_ID=$ordinal" > /etc/broker-id.env;
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
              name: kafka
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  name: broker-id-config
                  key: KAFKA_BROKER_ID
            - name: KAFKA_PROCESS_ROLES
              value: broker
            - name: KAFKA_NODE_ID
              valueFrom:
                configMapKeyRef:
                  name: broker-id-config
                  key: KAFKA_BROKER_ID
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-$(POD_NAME).kafka-svc.default.svc.cluster.local:9092,EXTERNAL://0.0.0.0:30092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:30092
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-0.kafka-svc.default.svc.cluster.local:9093,2@kafka-1.kafka-svc.default.svc.cluster.local:9093,3@kafka-2.kafka-svc.default.svc.cluster.local:9093"
            - name: KAFKA_LISTENER_NAME_CONTROLLER_QUORUM_PORT
              value: "9093"
            - name: CLUSTER_ID
              value: "test1234"
          envFrom:
            - configMapRef:
                name: broker-id-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-id-config
  namespace: default
data:
  KAFKA_BROKER_ID: ""
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: default
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      nodePort: 30092