create table if not exists report (
    id bigint generated by default as identity,
    report_member_id uuid,
    resource_type integer,
    resource_id uuid,
    status integer,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    primary key (id)
);

create table if not exists report_detail (
    id bigint generated by default as identity,
    report_id bigint,
    content varchar(500),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    primary key (id)
);

alter table if exists report_detail
   add constraint report_detail_report_id_fk
   foreign key (report_id)
   references report;